shared:
  node_container: &node_container
    language: node_js
    node_js:
      - 10.19.0
    before_install:
      - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.21.1
      - export PATH="$HOME/.yarn/bin:$PATH"
    install:
      - yarn install --production=false --frozen-lockfile
    cache: yarn

matrix:
  include:
    - <<: *node_container
      name: 'Node - build, type-check, and end-to-end tests'
      script:
        - yarn build --verbose
        - yarn test:ci --testPathPattern e2e.test
    - <<: *node_container
      name: 'Node - unit tests'
      script:
        - yarn test:ci --testPathIgnorePatterns e2e.test
        - yarn codecov
    - <<: *node_container
      name: 'Node - lint'
      script:
        - yarn lint
        - yarn ci:lint-docs
# notifications:
#   slack:
#     on_pull_requests: false
#     secure: ...
